import type { RouteDoc } from './visibility'

const uuidParam = (name: string, description: string) => ({
  name,
  in: 'path',
  required: true,
  description,
  schema: { type: 'string', format: 'uuid' },
})

const tenantHeaderParam = {
  name: 'x-tenant-id',
  in: 'header',
  required: true,
  description: 'Tenant UUID resolved by the caller. Supabase and Worker checks still enforce tenant isolation.',
  schema: { type: 'string', format: 'uuid' },
}

const errorJson = {
  description: 'Error response',
  content: {
    'application/json': {
      schema: {
        type: 'object',
        properties: {
          error: { type: 'string' },
        },
      },
    },
  },
}

export const OPENAPI_ROUTE_CATALOG: RouteDoc[] = [
  {
    boundary: 'public',
    method: 'get',
    path: '/health',
    operationId: 'edgeHealth',
    summary: 'Worker health check',
    description: 'Simple liveness endpoint for the awcms-edge Worker.',
    tags: ['Health'],
    scope: 'public',
    tenantContext: 'none',
    r2: false,
    softDeleteAware: false,
    responses: {
      '200': {
        description: 'Worker is healthy',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: { type: 'boolean', const: true },
                service: { type: 'string', const: 'awcms-edge' },
              },
              required: ['ok', 'service'],
            },
          },
        },
      },
    },
  },
  {
    boundary: 'public',
    method: 'get',
    path: '/public/media/{storageKey}',
    operationId: 'getPublicMediaObject',
    summary: 'Serve a public media object',
    description: 'Returns a public R2-backed media object when the metadata row is uploaded, public, and not soft-deleted. The route only accepts canonical tenant-prefixed keys under `tenants/<tenant_id>/...` and rejects malformed keys, traversal-like segments, and the reserved protected namespace.',
    tags: ['Public Delivery'],
    scope: 'public',
    tenantContext: 'none',
    r2: true,
    softDeleteAware: true,
    parameters: [
      {
        name: 'storageKey',
        in: 'path',
        required: true,
        description: 'Canonical public storage key under `/public/media/*`, for example `tenants/<tenant_id>/<file>`. Keys under `tenants/<tenant_id>/protected/...` are never valid on this route.',
        schema: { type: 'string' },
      },
    ],
    responses: {
      '200': { description: 'Media object stream' },
      '400': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'public',
    method: 'get',
    path: '/public/sitemap',
    operationId: 'getTenantSitemap',
    summary: 'Generate tenant sitemap XML',
    description: 'Builds a sitemap for a tenant using published, public, and non-deleted content only. Tenant identity may be resolved from `tenant_id` or `domain`; when both are supplied they must resolve to the same tenant or the route fails closed.',
    tags: ['Public Delivery'],
    scope: 'public',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: true,
    parameters: [
      {
        name: 'domain',
        in: 'query',
        required: false,
        description: 'Tenant domain used to resolve the sitemap tenant. If combined with `tenant_id`, both values must resolve to the same tenant.',
        schema: { type: 'string' },
      },
      {
        name: 'tenant_id',
        in: 'query',
        required: false,
        description: 'Tenant UUID used to resolve the sitemap tenant. If combined with `domain`, both values must resolve to the same tenant.',
        schema: { type: 'string', format: 'uuid' },
      },
    ],
    responses: {
      '200': {
        description: 'XML sitemap',
        content: {
          'application/xml': {
            schema: { type: 'string' },
          },
        },
      },
      '404': {
        description: 'Tenant was not found',
        content: {
          'application/xml': {
            schema: { type: 'string' },
          },
        },
      },
      '400': {
        description: 'Tenant/domain mismatch or invalid tenant context',
        content: {
          'application/xml': {
            schema: { type: 'string' },
          },
        },
      },
    },
  },
  {
    boundary: 'public',
    method: 'get',
    path: '/functions/v1/serve-sitemap',
    operationId: 'redirectServeSitemap',
    summary: 'Legacy sitemap compatibility redirect',
    description: 'Compatibility route that redirects legacy consumers to `/public/sitemap`.',
    tags: ['Public Delivery'],
    scope: 'public',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: true,
    deprecated: true,
    responses: {
      '301': { description: 'Redirect to `/public/sitemap`' },
    },
  },
  {
    boundary: 'public',
    method: 'post',
    path: '/functions/v1/verify-turnstile',
    operationId: 'verifyTurnstile',
    summary: 'Verify a Turnstile token',
    description: 'Validates a Turnstile token at the edge. This endpoint is descriptive only and does not replace Supabase authorization.',
    tags: ['Human Verification'],
    scope: 'public',
    tenantContext: 'none',
    r2: false,
    softDeleteAware: false,
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              token: { type: 'string' },
            },
            required: ['token'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'Verification result',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: { type: 'boolean' },
                ip: { type: 'string', nullable: true },
              },
            },
          },
        },
      },
      '400': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'public',
    method: 'get',
    path: '/functions/v1/extensions/events/public',
    operationId: 'listPublicEventsExtensionContent',
    summary: 'Read published public events extension content',
    description: 'Returns published event records for tenants with the Events extension active. Tenant identity may be resolved from `tenantId`, `tenant_id`, or `domain`; when both tenant and domain inputs are supplied they must resolve to the same tenant.',
    tags: ['Extensions', 'Public Delivery'],
    scope: 'public',
    tenantContext: 'required',
    r2: false,
    softDeleteAware: true,
    parameters: [
      {
        name: 'tenantId',
        in: 'query',
        required: false,
        description: 'Tenant UUID used to resolve public events. May be used together with `domain` only when both resolve to the same tenant.',
        schema: { type: 'string', format: 'uuid' },
      },
      {
        name: 'domain',
        in: 'query',
        required: false,
        description: 'Tenant domain used to resolve public events. May be used instead of `tenantId`.',
        schema: { type: 'string' },
      },
      {
        name: 'slug',
        in: 'query',
        required: false,
        schema: { type: 'string' },
      },
      {
        name: 'limit',
        in: 'query',
        required: false,
        schema: { type: 'integer', minimum: 1, maximum: 48, default: 12 },
      },
    ],
    responses: {
      '200': { description: 'Published events payload' },
      '400': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'public',
    method: 'get',
    path: '/functions/v1/extensions/public-modules',
    operationId: 'listPublicModules',
    summary: 'Read tenant public extension modules',
    description: 'Returns public module descriptors for extensions active on the requested tenant. Tenant identity may be resolved from `tenantId`, `tenant_id`, or `domain`; when both tenant and domain inputs are supplied they must resolve to the same tenant.',
    tags: ['Extensions', 'Public Delivery'],
    scope: 'public',
    tenantContext: 'required',
    r2: false,
    softDeleteAware: true,
    parameters: [
      {
        name: 'tenantId',
        in: 'query',
        required: false,
        description: 'Tenant UUID used to resolve public modules. May be used together with `domain` only when both resolve to the same tenant.',
        schema: { type: 'string', format: 'uuid' },
      },
      {
        name: 'domain',
        in: 'query',
        required: false,
        description: 'Tenant domain used to resolve public modules. May be used instead of `tenantId`.',
        schema: { type: 'string' },
      },
    ],
    responses: {
      '200': { description: 'Public module manifest payload' },
      '400': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'public',
    method: 'post',
    path: '/functions/v1/manage-users',
    operationId: 'submitAccountApplication',
    summary: 'Submit a public account application',
    description: 'Public application flow for account requests. This public documentation only covers `action=submit_application`; authenticated administrative actions are documented separately in protected admin surfaces.',
    tags: ['Applications'],
    scope: 'public',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: false,
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              action: { type: 'string', enum: ['submit_application'] },
              email: { type: 'string', format: 'email' },
              full_name: { type: 'string' },
              tenant_id: { type: 'string', format: 'uuid', nullable: true },
              turnstileToken: { type: 'string' },
            },
            required: ['action', 'email', 'full_name', 'turnstileToken'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Application accepted' },
      '400': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/api/media/upload-session',
    operationId: 'createMediaUploadSession',
    summary: 'Create a media upload session',
    description: 'Creates a tenant-scoped upload session and returns the upload and finalize URLs. Supabase Auth, RLS, and ABAC remain authoritative.',
    tags: ['Media'],
    scope: 'tenant',
    permission: 'tenant.files.create | tenant.files.manage',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: false,
    security: ['supabaseBearerAuth'],
    parameters: [tenantHeaderParam],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              fileName: { type: 'string' },
              mimeType: { type: 'string' },
              sizeBytes: { type: 'integer', minimum: 1 },
              categoryId: { type: 'string', format: 'uuid', nullable: true },
              folder: { type: 'string', nullable: true },
              accessControl: { type: 'string', enum: ['public', 'private'], nullable: true },
              sessionBoundAccess: { type: 'boolean', default: false },
            },
            required: ['fileName', 'mimeType', 'sizeBytes'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Upload session created' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/api/media/upload/{sessionId}/finalize',
    operationId: 'finalizeMediaUpload',
    summary: 'Queue media upload finalization',
    description: 'Queues or executes upload finalization for a pending upload session owned by the authenticated uploader.',
    tags: ['Media'],
    scope: 'tenant',
    permission: 'tenant.files.create | tenant.files.manage',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: false,
    security: ['supabaseBearerAuth'],
    parameters: [uuidParam('sessionId', 'Pending upload session UUID')],
    responses: {
      '202': { description: 'Upload finalization accepted' },
      '401': errorJson,
      '403': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'get',
    path: '/api/media/upload/{sessionId}/status',
    operationId: 'getMediaUploadStatus',
    summary: 'Read media upload finalization status',
    description: 'Returns the current finalization state for an upload session owned by the authenticated uploader.',
    tags: ['Media'],
    scope: 'tenant',
    permission: 'tenant.files.read',
    tenantContext: 'required',
    r2: false,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [uuidParam('sessionId', 'Upload session UUID')],
    responses: {
      '200': { description: 'Current upload status payload' },
      '401': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'delete',
    path: '/api/media/{id}/permanent',
    operationId: 'permanentlyDeleteMediaObject',
    summary: 'Permanently delete a trashed media object',
    description: 'Deletes a previously soft-deleted media object from storage and removes the database row through a guarded RPC.',
    tags: ['Media'],
    scope: 'tenant',
    permission: 'tenant.files.permanent_delete',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [uuidParam('id', 'Media object UUID'), tenantHeaderParam],
    responses: {
      '200': { description: 'Media object permanently deleted' },
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
      '409': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'get',
    path: '/api/media/file/{id}/access',
    operationId: 'getMediaAccessUrl',
    summary: 'Resolve an access URL for a media object',
    description: 'Returns either a public delivery URL or a session-bounded signed URL for an uploaded media object visible through Supabase policies.',
    tags: ['Media'],
    scope: 'tenant',
    permission: 'tenant.files.read',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [
      uuidParam('id', 'Media object UUID'),
      {
        name: 'maxAgeSeconds',
        in: 'query',
        required: false,
        schema: { type: 'integer', minimum: 1 },
      },
    ],
    responses: {
      '200': { description: 'Resolved media access URL payload' },
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'get',
    path: '/api/media/file/{id}',
    operationId: 'streamProtectedMediaFile',
    summary: 'Stream a protected media object',
    description: 'Streams a protected media object after Supabase-visible access is confirmed.',
    tags: ['Media'],
    scope: 'tenant',
    permission: 'tenant.files.read',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [uuidParam('id', 'Media object UUID')],
    responses: {
      '200': { description: 'Media object stream' },
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/api/public/rebuild',
    operationId: 'queuePublicPortalRebuild',
    summary: 'Queue a tenant public portal rebuild',
    description: 'Queues a tenant-scoped public rebuild after verifying tenant context and content-management permissions.',
    tags: ['Public Portal'],
    scope: 'tenant',
    permission: 'tenant.page.update | tenant.blog.update | tenant.menu.update',
    tenantContext: 'required',
    r2: false,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [tenantHeaderParam],
    requestBody: {
      required: false,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              resource: { type: 'string', nullable: true },
              action: { type: 'string', nullable: true },
            },
          },
        },
      },
    },
    responses: {
      '202': { description: 'Rebuild queued' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/functions/v1/content-transform',
    operationId: 'applyContentTransform',
    summary: 'Apply transformed blog content',
    description: 'Updates a tenant blog content payload after bearer authentication, tenant scoping, and blog update permission checks.',
    tags: ['Content'],
    scope: 'tenant',
    permission: 'tenant.blog.update',
    tenantContext: 'required',
    r2: false,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [tenantHeaderParam],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              blog_id: { type: 'string', format: 'uuid' },
              transformed: { type: 'object' },
            },
            required: ['blog_id', 'transformed'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Transformed blog content persisted' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/functions/v1/extensions-lifecycle',
    operationId: 'manageExtensionLifecycle',
    summary: 'Run an extension lifecycle action',
    description: 'Runs catalog, install, activation, upgrade, and health-check actions for the extension system. The exact ABAC grant depends on the lifecycle action.',
    tags: ['Extensions'],
    scope: 'tenant',
    permission: 'platform.extensions.manage | platform.extensions.read | tenant.setting.update | tenant.setting.read',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              action: {
                type: 'string',
                enum: ['catalog-register', 'install', 'activate', 'deactivate', 'config-update', 'uninstall', 'upgrade', 'health-check'],
              },
              tenantId: { type: 'string', format: 'uuid', nullable: true },
            },
            required: ['action'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Lifecycle action completed' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/functions/v1/manage-users',
    operationId: 'manageUsersAdminActions',
    summary: 'Run authenticated user-management actions',
    description: 'Protected `manage-users` actions for invitations, creation, approval, updates, deletes, and account-request review. The public application submission flow is documented separately in the public spec.',
    tags: ['Identity'],
    scope: 'tenant',
    permission: 'tenant.user.update | platform.tenant.read',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              action: {
                type: 'string',
                enum: ['approve_application_admin', 'approve_application_super_admin', 'reject_application', 'create', 'invite', 'update', 'delete'],
              },
              email: { type: 'string', format: 'email', nullable: true },
              password: { type: 'string', nullable: true },
              full_name: { type: 'string', nullable: true },
              role_id: { type: 'string', format: 'uuid', nullable: true },
              user_id: { type: 'string', format: 'uuid', nullable: true },
              tenant_id: { type: 'string', format: 'uuid', nullable: true },
              request_id: { type: 'string', format: 'uuid', nullable: true },
              reason: { type: 'string', nullable: true },
            },
            required: ['action'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'User-management action completed' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/functions/v1/get-client-ip',
    operationId: 'getAuthenticatedClientIp',
    summary: 'Resolve the authenticated caller IP',
    description: 'Returns the request IP for an authenticated caller after bearer-token validation.',
    tags: ['Identity'],
    scope: 'tenant',
    permission: 'tenant.user.read',
    tenantContext: 'none',
    r2: false,
    softDeleteAware: false,
    security: ['supabaseBearerAuth'],
    responses: {
      '200': { description: 'Resolved client IP payload' },
      '401': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'post',
    path: '/functions/v1/xendit-payment',
    operationId: 'checkXenditPaymentCapability',
    summary: 'Check Xendit payment route capability',
    description: 'Authenticated capability probe for the Xendit payment integration route. The current runtime returns `501` because the integration is not configured.',
    tags: ['Messaging'],
    scope: 'tenant',
    permission: 'tenant.orders.read',
    tenantContext: 'none',
    r2: false,
    softDeleteAware: false,
    security: ['supabaseBearerAuth'],
    responses: {
      '501': { description: 'Xendit integration is not configured' },
      '401': errorJson,
    },
  },
  {
    boundary: 'admin',
    method: 'get',
    path: '/functions/v1/extensions/events/health',
    operationId: 'getEventsExtensionHealth',
    summary: 'Inspect tenant events extension health',
    description: 'Returns published and upcoming counts for the Events extension after tenant resolution and permission checks.',
    tags: ['Extensions'],
    scope: 'tenant',
    permission: 'tenant.events.read',
    tenantContext: 'required',
    r2: false,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    parameters: [
      {
        name: 'tenantId',
        in: 'query',
        required: false,
        schema: { type: 'string', format: 'uuid' },
      },
    ],
    responses: {
      '200': { description: 'Events extension health payload' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'put',
    path: '/api/media/upload-proxy/{sessionId}',
    operationId: 'putLocalDevUploadProxy',
    summary: 'Write upload bytes through the local-dev proxy',
    description: 'Local-dev upload proxy used only when direct presigned uploads are not available. Not part of the public runtime docs.',
    tags: ['Operational'],
    scope: 'tenant',
    permission: 'tenant.files.create | tenant.files.manage',
    tenantContext: 'none',
    r2: true,
    softDeleteAware: false,
    parameters: [uuidParam('sessionId', 'Upload session UUID')],
    responses: {
      '200': { description: 'Upload bytes accepted' },
      '400': errorJson,
      '404': errorJson,
      '409': errorJson,
      '410': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/api/media/import-local',
    operationId: 'importLocalMediaMirror',
    summary: 'Import local media metadata and object bytes',
    description: 'Local-only maintenance route used to reconcile media objects into the local Worker storage emulator.',
    tags: ['Operational'],
    scope: 'platform',
    permission: 'platform.sync.manage',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    responses: {
      '200': { description: 'Local media import completed' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/api/media/cleanup-local-duplicates',
    operationId: 'cleanupLocalMediaDuplicates',
    summary: 'Soft-delete duplicate local media objects',
    description: 'Local-only maintenance route used after media reconciliation to clean up duplicate rows and objects.',
    tags: ['Operational'],
    scope: 'platform',
    permission: 'platform.sync.manage',
    tenantContext: 'required',
    r2: true,
    softDeleteAware: true,
    security: ['supabaseBearerAuth'],
    responses: {
      '200': { description: 'Duplicate cleanup completed' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/api/mailketing',
    operationId: 'invokeMailketingApiAlias',
    summary: 'Invoke the Mailketing integration via API alias',
    description: 'Operational Mailketing integration alias for send, subscribe, credits, and lists actions. The `send` action now requires a bearer session plus tenant context that resolves to the authenticated user and permission to send or manage notifications; non-send actions remain synchronous compatibility helpers.',
    tags: ['Messaging', 'Operational'],
    scope: 'tenant',
    permission: 'tenant.notifications.send | tenant.notifications.manage',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: false,
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              action: { type: 'string', enum: ['send', 'subscribe', 'credits', 'lists'] },
            },
            required: ['action'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Mailketing sync action completed' },
      '202': { description: 'Mailketing send action queued' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/functions/v1/mailketing',
    operationId: 'invokeMailketingFunctionAlias',
    summary: 'Invoke the Mailketing integration via compatibility alias',
    description: 'Compatibility alias for the Mailketing integration with the same operational trust boundary as `/api/mailketing`. The `send` action requires a bearer session, matching tenant context, and notification send/manage permission.',
    tags: ['Messaging', 'Operational'],
    scope: 'tenant',
    permission: 'tenant.notifications.send | tenant.notifications.manage',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: false,
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              action: { type: 'string', enum: ['send', 'subscribe', 'credits', 'lists'] },
            },
            required: ['action'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Mailketing sync action completed' },
      '202': { description: 'Mailketing send action queued' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/functions/v1/mailketing-webhook',
    operationId: 'ingestMailketingWebhook',
    summary: 'Ingest Mailketing delivery webhook events',
    description: 'Internal callback used to record Mailketing events and update email status metadata.',
    tags: ['Messaging', 'Operational'],
    scope: 'platform',
    permission: 'platform.notifications.manage',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: false,
    responses: {
      '200': { description: 'Webhook event ingested' },
      '400': errorJson,
      '500': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/api/admin/queue/replay',
    operationId: 'replayDeadLetterQueueMessage',
    summary: 'Replay a dead-letter queue message',
    description: 'Platform-only operational route that re-enqueues a dead-letter message onto its live queue and records replay metadata.',
    tags: ['Operational'],
    scope: 'platform',
    permission: 'platform.docs.read',
    tenantContext: 'none',
    r2: false,
    softDeleteAware: false,
    security: ['supabaseBearerAuth'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              id: { type: 'string', format: 'uuid' },
            },
            required: ['id'],
          },
        },
      },
    },
    responses: {
      '200': { description: 'Dead-letter message replayed' },
      '400': errorJson,
      '401': errorJson,
      '403': errorJson,
      '404': errorJson,
      '409': errorJson,
    },
  },
  {
    boundary: 'internal',
    method: 'post',
    path: '/webhooks/public-rebuild/smandapbun',
    operationId: 'queueSmandapbunPublicRebuildWebhook',
    summary: 'Queue the SMANDAPBUN public rebuild callback',
    description: 'Server-to-server rebuild callback guarded by a shared secret header. This route is never exposed via public runtime docs.',
    tags: ['Operational', 'Public Portal'],
    scope: 'platform',
    permission: 'platform.docs.read',
    tenantContext: 'optional',
    r2: false,
    softDeleteAware: false,
    security: ['secretHeaderAuth'],
    responses: {
      '202': { description: 'Rebuild job queued' },
      '401': errorJson,
      '500': errorJson,
    },
  },
] as const
