-- Database Hardening Migration
-- Generated by AWCMS Assistant
-- Date: 2026-02-15

-- 1. Security Fixes (Permissive Policies)
-- Enforce tenant isolation on tables that previously had permissive access


-- categories
DROP POLICY IF EXISTS "categories_select_unified" ON "public"."categories";
CREATE POLICY "categories_select_unified" ON "public"."categories"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());

-- content_translations
-- Note: Replaced "post_files_read_all" style permissive policy
DROP POLICY IF EXISTS "content_translations_read_all" ON "public"."content_translations";
CREATE POLICY "content_translations_read_all" ON "public"."content_translations"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());

-- menu_permissions
DROP POLICY IF EXISTS "menu_permissions_select_public" ON "public"."menu_permissions";
CREATE POLICY "menu_permissions_select_public" ON "public"."menu_permissions"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());

-- page_files
DROP POLICY IF EXISTS "page_files_read_all" ON "public"."page_files";
CREATE POLICY "page_files_read_all" ON "public"."page_files"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());

-- template_strings
DROP POLICY IF EXISTS "template_strings_select_unified" ON "public"."template_strings";
CREATE POLICY "template_strings_select_unified" ON "public"."template_strings"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());


-- admin_menus
DROP POLICY IF EXISTS "admin_menus_select_unified" ON "public"."admin_menus";
CREATE POLICY "admin_menus_select_unified" ON "public"."admin_menus"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());

-- tenant_resource_registry
DROP POLICY IF EXISTS "tenant_resource_registry_select" ON "public"."tenant_resource_registry";
CREATE POLICY "tenant_resource_registry_select" ON "public"."tenant_resource_registry"
FOR SELECT USING (("tenant_id" = "public"."current_tenant_id"()) OR "public"."is_platform_admin"());


-- 2. Performance Fixes (Missing Indexes)
-- Add indexes for tenant_id columns that were missing them

CREATE INDEX IF NOT EXISTS "idx_analytics_daily_tenant_id" ON "public"."analytics_daily" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_analytics_events_tenant_id" ON "public"."analytics_events" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_mobile_app_config_tenant_id" ON "public"."mobile_app_config" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_modules_tenant_id" ON "public"."modules" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_tenant_channels_tenant_id" ON "public"."tenant_channels" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_tenant_resource_rules_tenant_id" ON "public"."tenant_resource_rules" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_tenant_role_links_tenant_id" ON "public"."tenant_role_links" ("tenant_id");
