#!/usr/bin/env python3

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import subprocess


REPO_ROOT = Path(__file__).resolve().parent.parent
CHECKLIST_PATH = REPO_ROOT / "setup-output" / "deployment-checklist.md"
LOCAL_DB_URL = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"


class SetupCancelled(Exception):
    pass


@dataclass
class PromptField:
    key: str
    prompt: str
    required: bool = True


def ask(field: PromptField) -> str:
    value = input(f"{field.prompt}: ").strip()
    if field.required and not value:
        raise SetupCancelled(f"Missing required value for {field.key}. Setup cancelled.")
    return value


def ask_yes_no(prompt: str) -> bool:
    value = input(f"{prompt} [y/n]: ").strip().lower()
    if value not in {"y", "n"}:
        raise SetupCancelled("Confirmation not provided. Setup cancelled.")
    return value == "y"


def ensure_overwrite(path: Path) -> None:
    if path.exists() and not ask_yes_no(f"{path} already exists. Overwrite"):  # noqa: PLR2004
        raise SetupCancelled(f"Refused to overwrite {path}. Setup cancelled.")


def write_env_file(path: Path, values: dict[str, str]) -> None:
    ensure_overwrite(path)
    content = "\n".join(f"{key}={value}" for key, value in values.items()) + "\n"
    path.write_text(content, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bootstrap AWCMS local environment files")
    parser.add_argument(
        "--config-json",
        type=Path,
        help="Path to a JSON file containing all required setup values for non-interactive mode",
    )
    parser.add_argument(
        "--force-fresh-check-skip",
        action="store_true",
        help="Skip the local tenant-data safety check. Use only for controlled automation on disposable environments.",
    )
    return parser.parse_args()


def load_json_config(path: Path, fields: list[PromptField]) -> dict[str, str]:
    if not path.exists():
        raise SetupCancelled(f"JSON config not found: {path}")

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SetupCancelled(f"Invalid JSON config: {exc}") from exc

    if not isinstance(payload, dict):
        raise SetupCancelled("JSON config must be an object of key/value pairs")

    values: dict[str, str] = {}
    for field in fields:
        raw_value = payload.get(field.key, "")
        value = str(raw_value).strip() if raw_value is not None else ""
        if field.required and not value:
            raise SetupCancelled(f"Missing required value for {field.key} in JSON config. Setup cancelled.")
        values[field.key] = value

    return values


def write_deployment_checklist(values: dict[str, str], configure_mobile: bool) -> None:
    CHECKLIST_PATH.parent.mkdir(parents=True, exist_ok=True)
    checklist = f"""# Deployment Checklist

Generated by `scripts/setup_awcms_environment.py`.

## Local Files Written

- `awcms/.env.local`
- `awcms-public/primary/.env.local`
- `awcms-public/smandapbun/.env.local`
- `awcms-edge/.dev.vars`
- `awcms-mcp/.env`
{'- `awcms-mobile/primary/.env`' if configure_mobile else '- Mobile env skipped'}

## Mirror These Values Into Deployment Systems

### Cloudflare Pages - Admin

- `VITE_SUPABASE_URL`
- `VITE_SUPABASE_PUBLISHABLE_KEY`
- `VITE_EDGE_URL`
- `VITE_TURNSTILE_SITE_KEY`

### Cloudflare Pages - Primary Public

- `PUBLIC_SUPABASE_URL` = `{values['VITE_SUPABASE_URL']}`
- `PUBLIC_SUPABASE_PUBLISHABLE_KEY`
- `PUBLIC_TENANT_ID` = `{values['PRIMARY_TENANT_ID']}`
- `PUBLIC_TENANT_SLUG` = `primary`
- `PUBLIC_TURNSTILE_SITE_KEY`

### Cloudflare Pages - SMANDAPBUN Public

- `PUBLIC_SUPABASE_URL` = `{values['VITE_SUPABASE_URL']}`
- `PUBLIC_SUPABASE_PUBLISHABLE_KEY`
- `PUBLIC_TENANT_ID` = `{values['SMANDAPBUN_TENANT_ID']}`
- `PUBLIC_TENANT_SLUG` = `smandapbun`
- `PUBLIC_TURNSTILE_SITE_KEY`
- `CLOUDFLARE_ACCOUNT_ID`

### Cloudflare Worker Secrets / Vars

- `VITE_SUPABASE_URL`
- `VITE_SUPABASE_PUBLISHABLE_KEY`
- `SUPABASE_SECRET_KEY`
- `R2_ACCOUNT_ID`
- `R2_ACCESS_KEY_ID`
- `R2_SECRET_ACCESS_KEY`
- `R2_BUCKET_NAME`
- `TURNSTILE_SECRET_KEY`
- `MAILKETING_API_TOKEN`
- `MAILKETING_DEFAULT_LIST_ID`
- `GITHUB_REBUILD_TOKEN`
- `GITHUB_REBUILD_OWNER`
- `GITHUB_REBUILD_REPO`
- `GITHUB_REBUILD_EVENT_TYPE`
- `SMANDAPBUN_REBUILD_WEBHOOK_SECRET`

### GitHub Actions Secrets

- `VITE_SUPABASE_URL`
- `VITE_SUPABASE_PUBLISHABLE_KEY`
- `PUBLIC_TENANT_ID` for the primary public workflow
- Cloudflare deploy/runtime secrets used by the target workflows

## Post-Setup Validation

```bash
npx supabase start
npx supabase db push --local
bash scripts/verify_supabase_migration_consistency.sh
bash scripts/ci-validate-runtime.sh
```
"""
    CHECKLIST_PATH.write_text(checklist, encoding="utf-8")


def check_existing_local_tenants() -> None:
    try:
        result = subprocess.run(
            [
                "psql",
                LOCAL_DB_URL,
                "-At",
                "-c",
                "select slug from public.tenants where deleted_at is null limit 1;",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        return

    if result.returncode != 0:
        return

    if result.stdout.strip():
        raise SetupCancelled(
            "Existing local tenant data was detected. This bootstrap helper is for a fresh clone/local environment only and will not modify or remove existing tenant data. Reset your local data manually before running setup."
        )


def main() -> int:
    args = parse_args()
    print("AWCMS environment bootstrap")
    print("This script is intended for a fresh clone/local environment. If any required value is blank, setup stops without writing partial config.")

    if not args.force_fresh_check_skip:
        try:
            check_existing_local_tenants()
        except SetupCancelled as exc:
            print(exc)
            return 1
    else:
        print("Warning: skipping local tenant-data safety check (--force-fresh-check-skip).")

    fields = [
        PromptField("VITE_SUPABASE_URL", "Supabase URL"),
        PromptField("VITE_SUPABASE_PUBLISHABLE_KEY", "Supabase publishable key"),
        PromptField("SUPABASE_SECRET_KEY", "Supabase secret key"),
        PromptField("VITE_EDGE_URL", "Cloudflare Worker production URL"),
        PromptField("VITE_LOCAL_EDGE_URL", "Cloudflare Worker local URL", required=False),
        PromptField("CONTEXT7_API_KEY", "Context7 API key"),
        PromptField("VITE_TURNSTILE_SITE_KEY", "Turnstile site key"),
        PromptField("TURNSTILE_SECRET_KEY", "Turnstile secret key"),
        PromptField("CLOUDFLARE_ACCOUNT_ID", "Cloudflare account ID"),
        PromptField("CLOUDFLARE_API_TOKEN", "Cloudflare API token"),
        PromptField("R2_ACCOUNT_ID", "Cloudflare R2 account ID"),
        PromptField("R2_ACCESS_KEY_ID", "Cloudflare R2 access key ID"),
        PromptField("R2_SECRET_ACCESS_KEY", "Cloudflare R2 secret access key"),
        PromptField("R2_BUCKET_NAME", "Cloudflare R2 bucket name"),
        PromptField("R2_REGION", "Cloudflare R2 region"),
        PromptField("R2_CUSTOM_DOMAIN", "Cloudflare R2 custom domain"),
        PromptField("R2_S3_API_ENDPOINT", "Cloudflare R2 S3 API endpoint"),
        PromptField("MAILKETING_API_TOKEN", "Mailketing API token"),
        PromptField("MAILKETING_DEFAULT_LIST_ID", "Mailketing default list ID"),
        PromptField("GITHUB_REBUILD_TOKEN", "GitHub rebuild token"),
        PromptField("GITHUB_REBUILD_OWNER", "GitHub rebuild owner/org"),
        PromptField("GITHUB_REBUILD_REPO", "GitHub rebuild repo"),
        PromptField("GITHUB_REBUILD_EVENT_TYPE", "GitHub rebuild event type"),
        PromptField("SMANDAPBUN_REBUILD_WEBHOOK_SECRET", "SMANDAPBUN rebuild webhook secret"),
        PromptField("PRIMARY_TENANT_ID", "Primary tenant UUID"),
        PromptField("PRIMARY_TENANT_SLUG", "Primary tenant slug"),
        PromptField("SMANDAPBUN_TENANT_ID", "SMANDAPBUN tenant UUID", required=False),
        PromptField("SMANDAPBUN_TENANT_SLUG", "SMANDAPBUN tenant slug", required=False),
        PromptField("PUBLIC_TURNSTILE_SITE_KEY", "Public Turnstile site key"),
        PromptField("MCP_SUPABASE_DB_URL", "Supabase DB URL for awcms-mcp"),
    ]

    try:
        if args.config_json:
            values = load_json_config(args.config_json, fields)
            configure_mobile_raw = str(json.loads(args.config_json.read_text(encoding="utf-8")).get("CONFIGURE_MOBILE", "false")).strip().lower()
            if configure_mobile_raw not in {"true", "false", "1", "0", "yes", "no", "y", "n"}:
                raise SetupCancelled("CONFIGURE_MOBILE must be a boolean-like value in JSON config")
            configure_mobile = configure_mobile_raw in {"true", "1", "yes", "y"}
        else:
            values = {field.key: ask(field) for field in fields}
            configure_mobile = ask_yes_no("Configure awcms-mobile/primary/.env too")
    except SetupCancelled as exc:
        print(exc)
        return 1

    admin_env = {
        "VITE_SUPABASE_URL": values["VITE_SUPABASE_URL"],
        "VITE_SUPABASE_PUBLISHABLE_KEY": values["VITE_SUPABASE_PUBLISHABLE_KEY"],
        "VITE_EDGE_URL": values["VITE_EDGE_URL"],
        "VITE_LOCAL_EDGE_URL": values["VITE_LOCAL_EDGE_URL"] or "http://127.0.0.1:8787",
        "VITE_REMOTE_EDGE_URL": values["VITE_EDGE_URL"],
        "VITE_MEDIA_SECURE_SESSION_MAX_AGE_SECONDS": "900",
        "VITE_DEFAULT_SECURE_MEDIA_SESSION_MAX_AGE_SECONDS": "900",
        "SUPABASE_URL": values["VITE_SUPABASE_URL"],
        "SUPABASE_SECRET_KEY": values["SUPABASE_SECRET_KEY"],
        "MEDIA_SECURE_SESSION_MAX_AGE_SECONDS": "900",
        "CONTEXT7_API_KEY": values["CONTEXT7_API_KEY"],
        "VITE_TURNSTILE_SITE_KEY": values["VITE_TURNSTILE_SITE_KEY"],
        "R2_ACCOUNT_ID": values["R2_ACCOUNT_ID"],
        "R2_ACCESS_KEY_ID": values["R2_ACCESS_KEY_ID"],
        "R2_SECRET_ACCESS_KEY": values["R2_SECRET_ACCESS_KEY"],
        "R2_BUCKET_NAME": values["R2_BUCKET_NAME"],
        "R2_REGION": values["R2_REGION"],
        "R2_CUSTOM_DOMAIN": values["R2_CUSTOM_DOMAIN"],
        "R2_S3_API_ENDPOINT": values["R2_S3_API_ENDPOINT"],
        "CLOUDFLARE_API_TOKEN": values["CLOUDFLARE_API_TOKEN"],
        "CLOUDFLARE_ACCOUNT_ID": values["CLOUDFLARE_ACCOUNT_ID"],
        "MAILKETING_API_TOKEN": values["MAILKETING_API_TOKEN"],
        "MAILKETING_DEFAULT_LIST_ID": values["MAILKETING_DEFAULT_LIST_ID"],
        "VITE_DEV_TENANT_SLUG": "primary",
    }

    primary_public_env = {
        "VITE_SUPABASE_URL": values["VITE_SUPABASE_URL"],
        "VITE_SUPABASE_PUBLISHABLE_KEY": values["VITE_SUPABASE_PUBLISHABLE_KEY"],
        "PUBLIC_TURNSTILE_SITE_KEY": values["PUBLIC_TURNSTILE_SITE_KEY"],
        "PUBLIC_TENANT_ID": values["PRIMARY_TENANT_ID"],
        "PUBLIC_TENANT_SLUG": values["PRIMARY_TENANT_SLUG"],
        "VITE_PUBLIC_TENANT_ID": values["PRIMARY_TENANT_ID"],
    }

    smandapbun_public_env = {
        "PUBLIC_SUPABASE_URL": values["VITE_SUPABASE_URL"],
        "PUBLIC_SUPABASE_PUBLISHABLE_KEY": values["VITE_SUPABASE_PUBLISHABLE_KEY"],
        "PUBLIC_TURNSTILE_SITE_KEY": values["PUBLIC_TURNSTILE_SITE_KEY"],
        "PUBLIC_TENANT_ID": values["SMANDAPBUN_TENANT_ID"] or values["PRIMARY_TENANT_ID"],
        "PUBLIC_TENANT_SLUG": values["SMANDAPBUN_TENANT_SLUG"] or values["PRIMARY_TENANT_SLUG"],
        "CLOUDFLARE_ACCOUNT_ID": values["CLOUDFLARE_ACCOUNT_ID"],
    }

    edge_env = {
        "VITE_SUPABASE_URL": values["VITE_SUPABASE_URL"],
        "VITE_SUPABASE_PUBLISHABLE_KEY": values["VITE_SUPABASE_PUBLISHABLE_KEY"],
        "SUPABASE_SECRET_KEY": values["SUPABASE_SECRET_KEY"],
        "R2_ACCOUNT_ID": values["R2_ACCOUNT_ID"],
        "R2_ACCESS_KEY_ID": values["R2_ACCESS_KEY_ID"],
        "R2_SECRET_ACCESS_KEY": values["R2_SECRET_ACCESS_KEY"],
        "R2_BUCKET_NAME": values["R2_BUCKET_NAME"],
        "MEDIA_SECURE_SESSION_MAX_AGE_SECONDS": "900",
        "MAILKETING_API_TOKEN": values["MAILKETING_API_TOKEN"],
        "MAILKETING_DEFAULT_LIST_ID": values["MAILKETING_DEFAULT_LIST_ID"],
        "GITHUB_REBUILD_TOKEN": values["GITHUB_REBUILD_TOKEN"],
        "GITHUB_REBUILD_OWNER": values["GITHUB_REBUILD_OWNER"],
        "GITHUB_REBUILD_REPO": values["GITHUB_REBUILD_REPO"],
        "GITHUB_REBUILD_EVENT_TYPE": values["GITHUB_REBUILD_EVENT_TYPE"],
        "SMANDAPBUN_REBUILD_WEBHOOK_SECRET": values["SMANDAPBUN_REBUILD_WEBHOOK_SECRET"],
        "TURNSTILE_SECRET_KEY": values["TURNSTILE_SECRET_KEY"],
    }

    mcp_env = {
        "SUPABASE_DB_URL": values["MCP_SUPABASE_DB_URL"],
        "CONTEXT7_API_KEY": values["CONTEXT7_API_KEY"],
    }

    mobile_env = {
        "SUPABASE_URL": values["VITE_SUPABASE_URL"],
        "SUPABASE_PUBLISHABLE_KEY": values["VITE_SUPABASE_PUBLISHABLE_KEY"],
        "APP_NAME": "AWCMS Mobile",
        "APP_ENV": "development",
        "DEFAULT_TENANT_ID": values["PRIMARY_TENANT_ID"],
    }

    target_files = [
        (REPO_ROOT / "awcms" / ".env.local", admin_env),
        (REPO_ROOT / "awcms-public" / "primary" / ".env.local", primary_public_env),
        (REPO_ROOT / "awcms-public" / "smandapbun" / ".env.local", smandapbun_public_env),
        (REPO_ROOT / "awcms-edge" / ".dev.vars", edge_env),
        (REPO_ROOT / "awcms-mcp" / ".env", mcp_env),
    ]
    if configure_mobile:
        target_files.append((REPO_ROOT / "awcms-mobile" / "primary" / ".env", mobile_env))

    try:
        for target, _values in target_files:
            ensure_overwrite(target)

        for target, target_values in target_files:
            target.write_text(
                "\n".join(f"{key}={value}" for key, value in target_values.items()) + "\n",
                encoding="utf-8",
            )
    except SetupCancelled as exc:
        print(exc)
        return 1

    write_deployment_checklist(values, configure_mobile)

    print("\nSetup complete. Next steps:")
    print("1. npx supabase start")
    print("2. npx supabase db push --local")
    print("3. bash scripts/ci-validate-runtime.sh")
    print("4. Mirror the same values into Cloudflare Pages, Wrangler secrets, and GitHub Actions secrets")
    print(f"5. Review the generated deployment checklist: {CHECKLIST_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
